version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      BOT_USERNAME: $BOT_USERNAME
      DB_CHANNEL: $DB_CHANNEL
      LOG_CHANNEL: $LOG_CHANNEL
      DATABASE_URL: $DATABASE_URL
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      FORWARD_AS_COPY: $FORWARD_AS_COPY
      BROADCAST_AS_COPY: $BROADCAST_AS_COPY
      OTHER_USERS_CAN_SAVE_FILE: $OTHER_USERS_CAN_SAVE_FILE
